global:
  domain: "verlab.dcc.ufmg.br"
  user: "cadar"
  ssh_key: "~/.ssh/id_rsa.pub"
  ram_limit: 0 #TODO
hosts:
  proc1:
    cores: 4
  proc2:
    cores: 4
  proc3:
    cores: 4
  proc4:
    cores: 4
  proc5:
    cores: 4
  shaggydog:
    cores: 4
  eva:
    cores: 4
  dalek:
    cores: 4
  escher:
    cores: 4
  magritte:
    cores: 4
  wall-e:
    cores: 4

